// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "anlg-mobile-bridge.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "MobileBridgeSpec.h"

@interface MobileBridge : NSObject <NativeMobileBridgeSpec>
#else
#import <React/RCTBridgeModule.h>

@interface MobileBridge : NSObject <RCTBridgeModule>
#endif

@end