// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async authorizationStatus() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:todo|authorization_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async requestFullAccess() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:todo|request_full_access") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTodoLists() : Promise<Result<ReminderList[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:todo|list_todo_lists") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchTodos(filter: ReminderFilter) : Promise<Result<Reminder[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:todo|fetch_todos", { filter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readPath(path: string, limit: number | null, cursor: string | null) : Promise<Result<ReadPathResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:todo|read_path", { path, limit, cursor }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createTodo(input: CreateReminderInput) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:todo|create_todo", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async completeTodo(target: ReminderIdentifierInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:todo|complete_todo", { target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteTodo(target: ReminderIdentifierInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:todo|delete_todo", { target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async linearListTeams(connectionId: string, limit: number | null, cursor: string | null) : Promise<Result<CollectionPage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:todo|linear_list_teams", { connectionId, limit, cursor }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async linearListTickets(connectionId: string, teamId: string, query: string | null, limit: number | null, cursor: string | null) : Promise<Result<TicketPage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:todo|linear_list_tickets", { connectionId, teamId, query, limit, cursor }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubIssueState(owner: string, repo: string, number: number) : Promise<Result<GitHubIssueState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:todo|github_issue_state", { owner, repo, number }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubIssueDetail(owner: string, repo: string, number: number) : Promise<Result<Issue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:todo|github_issue_detail", { owner, repo, number }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubIssueComments(owner: string, repo: string, number: number) : Promise<Result<IssueComment[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:todo|github_issue_comments", { owner, repo, number }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
todoChangedEvent: TodoChangedEvent
}>({
todoChangedEvent: "plugin:todo:todo-changed-event"
})

/** user-defined constants **/



/** user-defined types **/

export type Alarm = { absolute_date: string | null; relative_offset: number | null; proximity: AlarmProximity | null; alarm_type: AlarmType | null; email_address: string | null; sound_name: string | null; url: string | null; structured_location: StructuredLocation | null }
export type AlarmProximity = "None" | "Enter" | "Leave"
export type AlarmType = "Display" | "Audio" | "Procedure" | "Email"
export type CalendarColor = { red: number; green: number; blue: number; alpha: number }
export type CalendarSource = { identifier: string; title: string; source_type: CalendarSourceType }
export type CalendarSourceType = "Local" | "Exchange" | "CalDav" | "MobileMe" | "Subscribed" | "Birthdays"
export type CalendarType = "Local" | "CalDav" | "Exchange" | "Subscription" | "Birthday"
export type CollectionPage = { items: CollectionRef[]; next_cursor: string | null }
export type CollectionRef = { id: string; 
/**
 * Display name. GitHub: "owner/repo", Linear: team name.
 */
name: string; 
/**
 * Short identifier. GitHub: "owner/repo", Linear: team key (e.g., "ENG").
 */
key: string | null; url: string | null }
export type CreateReminderInput = { title: string; list_id: string | null; notes: string | null; url: string | null; priority: ReminderPriority | null; due_date: DateComponents | null; start_date: DateComponents | null }
export type DateComponents = { date: string | null; time: string | null; time_zone: string | null }
export type GeoLocation = { latitude: number; longitude: number }
export type GitHubIssueState = "Open" | "Closed" | "Merged"
export type Issue = { id: number; number: number; title: string; body?: string | null; state: string; state_reason?: string | null; html_url: string; url: string; user?: User | null; assignees?: User[] | null; labels?: Label[] | null; milestone?: Milestone | null; pull_request?: IssuePullRequest | null; locked?: boolean | null; comments?: number | null; created_at: string; updated_at: string; closed_at?: string | null; closed_by?: User | null; draft?: boolean | null }
export type IssueComment = { id: number; body?: string | null; user?: User | null; created_at: string; updated_at: string; html_url: string }
export type IssuePullRequest = { url?: string | null; html_url?: string | null; diff_url?: string | null; patch_url?: string | null; merged_at?: string | null }
export type Label = { id: number; name: string; color?: string | null; description?: string | null }
export type LabelRef = { id: string; name: string; color: string | null }
export type Milestone = { id: number; number: number; title: string; description?: string | null; state: string }
export type PersonRef = { id: string | null; name: string | null; email: string | null; avatar_url: string | null }
export type PullRequestDetail = { is_draft: boolean; is_merged: boolean; source_branch: string | null; target_branch: string | null; merged_at: string | null; merged_by: PersonRef | null }
export type ReadPathResult = { kind: "reminder_lists"; data: ReminderList[] } | { kind: "reminders"; data: Reminder[] } | { kind: "collections"; data: CollectionPage } | { kind: "tickets"; data: TicketPage }
export type RecurrenceDayOfWeek = { weekday: Weekday; week_number: number | null }
export type RecurrenceEnd = { Count: number } | { Until: string }
export type RecurrenceFrequency = "Daily" | "Weekly" | "Monthly" | "Yearly"
export type RecurrenceRule = { frequency: RecurrenceFrequency; interval: number; days_of_week: RecurrenceDayOfWeek[]; days_of_month: number[]; months_of_year: number[]; weeks_of_year: number[]; days_of_year: number[]; set_positions: number[]; first_day_of_week: Weekday | null; end: RecurrenceEnd | null }
export type Reminder = { calendar_item_identifier: string; external_identifier: string; list: ReminderListRef; title: string; notes: string | null; url: string | null; priority: ReminderPriority; is_completed: boolean; completion_date: string | null; start_date_components: DateComponents | null; due_date_components: DateComponents | null; creation_date: string | null; last_modified_date: string | null; has_alarms: boolean; has_recurrence_rules: boolean; alarms: Alarm[]; recurrence_rules: RecurrenceRule[] }
export type ReminderFilter = { kind: ReminderFilterKind; list_ids: string[] | null }
export type ReminderFilterKind = "All" | { Incomplete: { from: string | null; to: string | null } } | { Completed: { from: string | null; to: string | null } }
export type ReminderIdentifierInput = { calendar_item_identifier: string | null; external_identifier: string | null; list_id: string | null }
export type ReminderList = { id: string; title: string; calendar_type: CalendarType; color: CalendarColor | null; allows_content_modifications: boolean; is_default: boolean; source: CalendarSource }
export type ReminderListRef = { id: string; title: string }
export type ReminderPriority = "None" | "High" | "Medium" | "Low"
export type StructuredLocation = { title: string; geo: GeoLocation | null; radius: number | null }
export type TicketKind = "issue" | "pull_request"
export type TicketPage = { items: TicketSummary[]; next_cursor: string | null }
export type TicketPriority = "urgent" | "high" | "medium" | "low" | "none"
export type TicketProviderType = "github" | "linear"
export type TicketState = "backlog" | "open" | "in_progress" | "done" | "closed"
export type TicketSummary = { provider: TicketProviderType; kind: TicketKind; 
/**
 * Provider-specific unique ID.
 */
id: string; 
/**
 * Numeric identifier (GitHub: number, Linear: number).
 */
number: number | null; collection: CollectionRef; title: string; state: TicketState; 
/**
 * Provider's original state string for display (e.g. "In Review", "merged").
 */
state_detail: string | null; priority: TicketPriority | null; author: PersonRef | null; assignees: PersonRef[]; labels: LabelRef[]; url: string; 
/**
 * ISO 8601.
 */
created_at: string; 
/**
 * ISO 8601.
 */
updated_at: string; 
/**
 * ISO 8601.
 */
closed_at: string | null; 
/**
 * Present only when kind == PullRequest.
 */
pull_request: PullRequestDetail | null; 
/**
 * Raw provider JSON for forward compatibility.
 */
raw: string }
export type TodoChangedEvent = null
export type User = { id: number; login: string; avatar_url?: string | null; html_url: string }
export type Weekday = "Sunday" | "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
