// @ts-nocheck
/** tauri-specta globals **/
import {
  Channel as TAURI_CHANNEL,
  invoke as TAURI_INVOKE,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {};

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

export type AddCommentOutput = { success: boolean; comment_url: string };
export type AddCommentParams = { issue_number: number; body: string };
export type CreateBillingPortalSessionOutput = { url: string };
export type CreateBillingPortalSessionParams = { return_url: string | null };
export type CreateIssueOutput = {
  success: boolean;
  issue_url: string;
  issue_number: number;
};
export type CreateIssueParams = {
  title: string;
  body: string;
  labels: string[] | null;
};
export type ListSubscriptionsParams = { status: string | null };
export type SearchIssueItem = {
  number: number;
  title: string;
  state: string;
  url: string;
  created_at: string;
  labels: string[];
};
export type SearchIssuesOutput = {
  total_results: number;
  issues: SearchIssueItem[];
};
export type SearchIssuesParams = {
  query: string;
  state: string | null;
  limit: number | null;
};
export type SubscriptionItem = {
  id: string;
  status: string;
  start_date: number | null;
  cancel_at_period_end: boolean;
  cancel_at: number | null;
  canceled_at: number | null;
  trial_start: number | null;
  trial_end: number | null;
};

type __EventObj__<T> = {
  listen: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
  once: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
  | { status: "ok"; data: T }
  | { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
  mappings: Record<keyof T, string>,
) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__<T[K]> & {
        (handle: __WebviewWindow__): __EventObj__<T[K]>;
      };
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T];

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg),
          }),
          get: (_, command: keyof __EventObj__<any>) => {
            switch (command) {
              case "listen":
                return (arg: any) => TAURI_API_EVENT.listen(name, arg);
              case "once":
                return (arg: any) => TAURI_API_EVENT.once(name, arg);
              case "emit":
                return (arg: any) => TAURI_API_EVENT.emit(name, arg);
            }
          },
        });
      },
    },
  );
}
