[package]
name = "denoise"
version = "0.1.0"
edition = "2024"

[features]
default = []
onnx = ["dep:anlg-onnx", "dep:realfft"]
coreml = ["onnx", "anlg-onnx/coreml"]

[dependencies]
anlg-onnx = { workspace = true, optional = true }
realfft = { workspace = true, optional = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
anlg-audio-snapshot = { workspace = true }
anlg-data = { workspace = true }
approx = { workspace = true }
criterion = { workspace = true }
dasp = { workspace = true }
hound = { workspace = true }
rodio = { workspace = true }

[[bench]]
name = "denoise_bench"
harness = false
required-features = ["onnx"]
