import { anthropic } from "@ai-sdk/anthropic";
import { generateObject } from "ai";
import fs from "fs";
import path from "path";
import { z } from "zod";

function extractContent(mdxContent) {
  const frontmatterMatch = mdxContent.match(/^---\n([\s\S]*?)\n---\n/);
  if (frontmatterMatch) {
    return mdxContent.slice(frontmatterMatch[0].length);
  }
  return mdxContent;
}

function extractFrontmatter(mdxContent) {
  const frontmatterMatch = mdxContent.match(/^---\n([\s\S]*?)\n---\n/);
  if (frontmatterMatch) {
    return frontmatterMatch[1];
  }
  return "";
}

function getFrontmatterLineCount(mdxContent) {
  const frontmatterMatch = mdxContent.match(/^---\n([\s\S]*?)\n---\n/);
  if (frontmatterMatch) {
    return frontmatterMatch[0].split("\n").length - 1;
  }
  return 0;
}

const issueSchema = z.object({
  issues: z.array(
    z.object({
      line: z.number().describe("Line number in the content (1-indexed)"),
      original: z
        .string()
        .describe("The exact original text that triggers the flag"),
      suggestion: z
        .string()
        .describe("Rewritten text that sounds human-written"),
      reason: z
        .string()
        .describe(
          "Which AI writing pattern this matches and why it reads as LLM output",
        ),
      category: z.enum([
        "antithesis-binary",
        "anaphoric-repetition",
        "staccato-fragments",
        "conversational-announcement",
        "clickbait-heading",
        "em-dash-reframe",
        "scare-quote-dismissal",
        "anthropomorphization",
        "marketing-framing",
        "metronomic-rhythm",
        "filler-phrase",
        "significance-inflation",
        "other",
      ]),
      severity: z
        .enum(["high", "medium", "low"])
        .describe(
          "high = obvious AI tell, medium = likely AI pattern, low = subtle but suspicious",
        ),
    }),
  ),
  score: z.object({
    directness: z
      .number()
      .describe("Score from 1 to 10: Statements or announcements?"),
    rhythm: z.number().describe("Score from 1 to 10: Varied or metronomic?"),
    trust: z
      .number()
      .describe("Score from 1 to 10: Respects reader intelligence?"),
    authenticity: z.number().describe("Score from 1 to 10: Sounds human?"),
    density: z.number().describe("Score from 1 to 10: Anything cuttable?"),
  }),
  summary: z
    .string()
    .describe(
      "Overall assessment: how much does this read like AI-generated content, and what are the dominant patterns?",
    ),
});

const SYSTEM_PROMPT = `You are an aggressive AI-slop detector for a technical blog. Your default assumption is that every piece of text you review WAS generated by an LLM, even if it was not. Your job is to find every pattern that would cause a technical reader to pattern-match the content as AI-generated.

AI writing is not about specific words. It is about how sentences and paragraphs are constructed. A sentence can use entirely original vocabulary and still read as AI-generated because of its rhetorical structure. Focus on structures first, vocabulary second.

# STRUCTURAL PATTERNS — These are the primary signals

## 1. Antithesis / Binary Framing
Setting up what something ISN'T before saying what it IS. This is the single most common AI rhetorical move.
- "This isn't X. This is Y." / "X isn't Y — it's Z."
- "Not because X. Because Y." / "Not because X. Not because Y. But because Z."
- "The answer isn't X. It's Y." / "The question isn't X. It's Y."
- "It feels like X. It's actually Y."
- "stops being X and starts being Y"
The pattern: any sentence pair where the first negates and the second affirms.
Fix: State the affirmative claim directly. Delete the negation setup.

Example:
  Before: "This isn't vibe coding hype. This is what actually happened."
  After: State the facts. Let the reader decide if it's hype.

## 2. Anaphoric Repetition for Dramatic Effect
Repeating the same word or phrase at the start of consecutive sentences/clauses to build rhetorical momentum. LLMs love this because it creates a sense of rhythm without requiring actual insight.
- "Not X. Not Y. But Z." (triple with turn)
- "No X. No Y. No Z." (staccato negation)
- "Time to X. Time to Y. Time to Z."
- Any repeated sentence opener used 2+ times for emphasis
Fix: Collapse into a single direct statement or vary the construction.

Example:
  Before: "Not because they need one. Not because their content is complicated. But because they feel like a 'real company' is supposed to have a CMS."
  After: "They adopt a CMS because it feels official, not because they need one."

## 3. Staccato Fragment Lists
Short punchy fragments stacked for emphasis. Feels manufactured.
- "No copying issues into a separate tool. No explaining the same problem twice."
- "Speed. Quality. Cost."
- "Just write. Ship. Repeat."
- Sentence fragments used as standalone paragraphs for dramatic weight
Fix: Use complete sentences. Combine fragments into flowing prose.

## 4. Conversational Announcements / Previews
Telling the reader what you're about to show them instead of just showing it.
- "Here's the thing:" / "Here's the curve:" / "Here's why:"
- "Let me explain:" / "Here's what I mean:"
- "Think about it:" / "Consider this:"
- "The pattern is clear:" / "The takeaway:"
Fix: Delete the announcement. Start with the content.

Example:
  Before: "Here's the curve: Day 1..."
  After: Just show the curve. The reader can see it.

## 5. Clickbait / Listicle Heading Formulas
Headings that use marketing templates rather than descriptive labels.
- "The Real Reason: [imperative]" / "The Real Reason You [verb]"
- "Final Verdict: Is X Worth It?" / "The Bottom Line"
- "X Things You Need to Know" / "Why X Matters"
- "[Number]. [Dramatic statement with period.]" 
- Imperative commands in headings: "Stay Nimble." "Think Bigger."
- "Is X Worth It?" as a heading
Fix: Use descriptive, specific headings. Say what the section contains.

Example:
  Before: "The Real Reason: You're Early. Stay Nimble."
  After: "Why early teams should avoid structure"

  Before: "Final Verdict: Is Devin AI Worth It?"
  After: "When Devin works and when it doesn't"

## 6. Em-Dash Reveals and Reframes
Using em-dashes to pivot to a reframe or revelation. LLMs use this as a dramatic pause device.
- "X isn't Y — it's Z."
- "The agent isn't replacing us — it's joining the conversation."
- Em-dash before a "twist" or reframe
Fix: Use periods. Make two sentences. Or use a comma if the clauses are short.

Example:
  Before: "The agent isn't replacing us—it's joining the conversation where it's already happening."
  After: "The agent participates in the same Slack threads where we discuss the problem."

## 7. Scare Quotes for Strawman Dismissal
Putting quotes around a term to set up a position the author will knock down or distance themselves from.
- 'These aren't "toy setups."'
- 'a "real company" is supposed to have'
- Using quotes to mark something as naive/wrong, then countering it
Fix: Either commit to the term or rephrase without the distancing quotes.

## 8. Anthropomorphization of Tools and Products
Giving human qualities to software, tools, or abstract concepts.
- "the agent joins the conversation" / "the CMS taps you on the shoulder"
- "your CMS says: 'you can't leave'"
- Tools that "understand", "figure out", "decide"
Fix: Describe what the tool does mechanically, not as if it has agency.

## 9. Marketing / Testimonial Framing
Prose that reads like ad copy or a product pitch rather than technical writing.
- "This is collaborative debugging without context switching."
- "This is what actually happened."
- "The key insight after X tasks:"
- "Our recommendation:"
- Sentences that read like a value proposition or tagline
- "You're not buying X. You're buying Y."
Fix: Describe specific outcomes. Remove framing that positions experience as a sales pitch.

## 10. Metronomic Rhythm
Sentences or paragraphs that all have the same length, cadence, or ending pattern.
- Three-item lists used for rhetorical effect (two or one is less AI-like)
- Every paragraph ending with a punchy one-liner
- Alternating short/long sentences in a predictable pattern
- Questions immediately followed by their answer
- Series of paragraphs all starting with the same construction
Fix: Vary sentence lengths unpredictably. Let some paragraphs trail off. Not every point needs a landing.

# VOCABULARY SIGNALS — Secondary (don't fixate on these, but note them)

These individual words/phrases are AI tells but catching them is less important than catching the structural patterns above:
- Throat-clearing: "Here's the thing", "The uncomfortable truth", "It turns out", "Let me be clear"
- Empty emphasis: "Full stop.", "Let that sink in.", "Make no mistake"
- Jargon: navigate, unpack, lean into, landscape, game-changer, deep dive, leverage, utilize, streamline, cutting-edge, paradigm shift, holistic, resonate
- Filler: "At its core", "In today's X", "It's worth noting", "At the end of the day", "When it comes to", "The reality is"
- Intensifiers: deeply, truly, fundamentally, inherently, seamlessly, effortlessly, incredibly, remarkably, profoundly
- Transitions: Moreover, Furthermore, Additionally, That said, That being said, Having said that
- Significance inflation: "stands/serves as", "is a testament to", "a pivotal/crucial/key role", "underscores", "evolving landscape", "setting the stage"

# SCORING

Rate 1-10 on each dimension:
| Dimension | Question |
|-----------|----------|
| Directness | Statements or announcements? |
| Rhythm | Varied or metronomic? |
| Trust | Respects reader intelligence? |
| Authenticity | Sounds human? |
| Density | Anything cuttable? |

Below 35/50 total: the text needs significant revision.

# BEFORE/AFTER EXAMPLES

Before: "Not because they need one. Not because their content is complicated. But because they feel like a 'real company' is supposed to have a CMS."
After: "They adopt a CMS because it feels official, not because they need one."
Why: Anaphoric triplet + scare quotes. The triple repetition and turn is a textbook AI rhetorical move.

Before: "This isn't vibe coding hype, or spinning up 10 Claude Code instances to burn tokens as fast as possible. This is what actually happened."
After: Remove entirely. Let the facts that follow speak for themselves.
Why: "This isn't X. This is Y." antithesis + testimonial framing.

Before: "This is collaborative debugging without context switching. No copying issues into a separate tool. No explaining the same problem twice."
After: "Both of us commented in the same thread. Devin used that context for its PR."
Why: Marketing tagline + staccato negation list.

Before: "The agent isn't replacing us—it's joining the conversation where it's already happening."
After: "Devin runs inside the same Slack thread where the problem was discussed."
Why: Em-dash reframe + anthropomorphization + binary antithesis.

Before: "Final Verdict: Is Devin AI Worth It?"
After: "When Devin works and when it doesn't"
Why: Clickbait heading formula.

Before: "Here's the thing: building products is hard. Not because the technology is complex. Because people are complex. Let that sink in."
After: "Building products is hard because people are unpredictable."
Why: Conversational announcement + binary contrast + emphasis crutch.

Before: "In today's fast-paced landscape, we need to lean into discomfort and navigate uncertainty with clarity."
After: "Move faster. Your competition is."
Why: Filler phrase + jargon stack.

# INSTRUCTIONS

1. Assume the text is LLM-generated by default. Be aggressive.
2. Prioritize structural patterns (sections 1-10) over individual word flags.
3. For each flag, provide a concrete rewrite that a human technical writer would produce.
4. A sentence can use entirely original words and still be AI slop because of its structure. Catch those.
5. Provide the exact line number where each issue occurs.
6. Give the exact original text and a human-sounding replacement.
7. Score the overall text on the 5 dimensions.
8. Pay special attention to: headings (clickbait formulas), opening paragraphs (throat-clearing), closing paragraphs (grand conclusions), and any sentence that reads like marketing copy.
9. Even if a phrase appears in a legitimate context, flag it if a reader could pattern-match it as AI output.
10. The goal is not to strip personality from writing. The goal is to remove patterns that make a technical reader think "this was written by ChatGPT."`;

async function checkSlop(content, contentWithLineNumbers) {
  const { object } = await generateObject({
    model: anthropic("claude-haiku-4-5"),
    schema: issueSchema,
    system: SYSTEM_PROMPT,
    prompt: `Review the following blog post content. Assume it was LLM-generated and aggressively flag every AI writing pattern you find. Be thorough — technical readers will notice even one slip.

Content with line numbers:
${contentWithLineNumbers}`,
  });

  return object;
}

function addLineNumbers(content) {
  return content
    .split("\n")
    .map((line, i) => `${i + 1}: ${line}`)
    .join("\n");
}

async function main() {
  const changedFiles =
    process.env.CHANGED_FILES?.trim().split(" ").filter(Boolean) || [];

  if (changedFiles.length === 0) {
    fs.writeFileSync(
      "slop-check-results.md",
      "## Slop Check Results\n\nNo article files were changed in this PR.",
    );
    return;
  }

  const results = [];

  for (const file of changedFiles) {
    if (!fs.existsSync(file)) {
      continue;
    }

    const fullContent = fs.readFileSync(file, "utf8");
    const articleContent = extractContent(fullContent);
    const frontmatter = extractFrontmatter(fullContent);
    const frontmatterLines = getFrontmatterLineCount(fullContent);

    const titleMatch =
      frontmatter.match(/display_title:\s*["']?(.+?)["']?\s*$/m) ||
      frontmatter.match(/meta_title:\s*["']?(.+?)["']?\s*$/m);
    const title = titleMatch ? titleMatch[1] : path.basename(file, ".mdx");

    console.log(`Slop-checking: ${file}`);

    try {
      const contentWithLineNumbers = addLineNumbers(articleContent);
      const feedback = await checkSlop(articleContent, contentWithLineNumbers);

      const totalScore =
        feedback.score.directness +
        feedback.score.rhythm +
        feedback.score.trust +
        feedback.score.authenticity +
        feedback.score.density;

      results.push({
        file,
        title,
        feedback,
        frontmatterLines,
        totalScore,
        contentLines: articleContent.split("\n"),
      });
    } catch (error) {
      results.push({
        file,
        title,
        feedback: null,
        error: error.message,
      });
    }
  }

  let markdown = "## AI Slop Check Results\n\n";
  markdown += `Reviewed ${results.length} article${results.length === 1 ? "" : "s"} for AI writing patterns.\n\n`;

  for (const result of results) {
    markdown += `### ${result.title}\n`;
    markdown += `\`${result.file}\`\n\n`;

    if (result.error) {
      markdown += `Error: ${result.error}\n\n`;
    } else {
      const { feedback, totalScore } = result;
      const passIcon = totalScore >= 35 ? "PASS" : "NEEDS REVISION";

      markdown += `**Score: ${totalScore}/50** (${passIcon})\n\n`;
      markdown += `| Dimension | Score |\n|-----------|-------|\n`;
      markdown += `| Directness | ${feedback.score.directness}/10 |\n`;
      markdown += `| Rhythm | ${feedback.score.rhythm}/10 |\n`;
      markdown += `| Trust | ${feedback.score.trust}/10 |\n`;
      markdown += `| Authenticity | ${feedback.score.authenticity}/10 |\n`;
      markdown += `| Density | ${feedback.score.density}/10 |\n\n`;

      markdown += `${feedback.summary}\n\n`;

      if (feedback.issues.length === 0) {
        markdown += `No AI writing patterns detected.\n\n`;
      } else {
        const highCount = feedback.issues.filter(
          (i) => i.severity === "high",
        ).length;
        const medCount = feedback.issues.filter(
          (i) => i.severity === "medium",
        ).length;
        const lowCount = feedback.issues.filter(
          (i) => i.severity === "low",
        ).length;

        markdown += `Found **${feedback.issues.length}** issue${feedback.issues.length === 1 ? "" : "s"}`;
        markdown += ` (${highCount} high, ${medCount} medium, ${lowCount} low)\n\n`;

        const severityOrder = ["high", "medium", "low"];
        const severityLabels = {
          high: "HIGH — Obvious AI Tell",
          medium: "MEDIUM — Likely AI Pattern",
          low: "LOW — Subtle but Suspicious",
        };

        for (const severity of severityOrder) {
          const issues = feedback.issues.filter((i) => i.severity === severity);
          if (issues.length === 0) continue;

          markdown += `#### ${severityLabels[severity]}\n\n`;

          for (const issue of issues) {
            const actualLine = issue.line + result.frontmatterLines;
            markdown += `**Line ${actualLine}** — \`${issue.category}\`\n`;
            markdown += `> ${issue.original}\n\n`;
            markdown += `${issue.reason}\n\n`;
            markdown += `<details>\n<summary>Suggested rewrite</summary>\n\n`;
            markdown += `\`\`\`suggestion\n${issue.suggestion}\n\`\`\`\n\n`;
            markdown += `</details>\n\n`;
          }
        }
      }
    }

    markdown += "---\n\n";
  }

  markdown +=
    "\n*Powered by Claude Haiku 4.5 with [stop-slop](https://github.com/hardikpandya/stop-slop) rules*";

  fs.writeFileSync("slop-check-results.md", markdown);
  console.log("Slop check complete. Results written to slop-check-results.md");
}

main().catch((error) => {
  console.error("Slop check failed:", error);
  fs.writeFileSync(
    "slop-check-results.md",
    `## AI Slop Check Results\n\nSlop check failed: ${error.message}`,
  );
  process.exit(1);
});
