// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  async describeUpload(
    jobId: string,
    attemptCount: number,
  ): Promise<Result<UploadDescriptor, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:attachment-sync|describe_upload", {
          jobId,
          attemptCount,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async prepareUpload(
    jobId: string,
    attemptCount: number,
    objectId: string,
    objectKey: string,
  ): Promise<Result<PreparedUpload, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:attachment-sync|prepare_upload", {
          jobId,
          attemptCount,
          objectId,
          objectKey,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async readUploadRange(
    jobId: string,
    attemptCount: number,
    cacheId: string,
    start: number,
    end: number,
  ): Promise<Result<number[], string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:attachment-sync|read_upload_range", {
          jobId,
          attemptCount,
          cacheId,
          start,
          end,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async beginSharedUploadOperation(
    operationId: string,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE(
          "plugin:attachment-sync|begin_shared_upload_operation",
          { operationId },
        ),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async cancelSharedUploadOperation(
    operationId: string,
  ): Promise<Result<boolean, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE(
          "plugin:attachment-sync|cancel_shared_upload_operation",
          { operationId },
        ),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async prepareSharedUpload(
    operationId: string,
    attachmentId: string,
    expected: SharedUploadVersion,
  ): Promise<Result<PreparedSharedUpload, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE(
          "plugin:attachment-sync|prepare_shared_upload",
          { operationId, attachmentId, expected },
        ),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async readSharedUploadRange(
    attachmentId: string,
    cacheId: string,
    expected: SharedUploadVersion,
    start: number,
    end: number,
  ): Promise<Result<number[], string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE(
          "plugin:attachment-sync|read_shared_upload_range",
          { attachmentId, cacheId, expected, start, end },
        ),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async validateSharedUpload(
    operationId: string,
    attachmentId: string,
    cacheId: string,
    expected: SharedUploadVersion,
  ): Promise<Result<boolean, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE(
          "plugin:attachment-sync|validate_shared_upload",
          { operationId, attachmentId, cacheId, expected },
        ),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async cleanupSharedUpload(cacheId: string): Promise<Result<boolean, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE(
          "plugin:attachment-sync|cleanup_shared_upload",
          { cacheId },
        ),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async prepareDeleteGuard(
    operationId: string,
    jobId: string,
    attemptCount: number,
    createGuard: boolean,
  ): Promise<Result<PreparedDeleteGuard, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE(
          "plugin:attachment-sync|prepare_delete_guard",
          { operationId, jobId, attemptCount, createGuard },
        ),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async commitDeleteGuard(
    operationId: string,
    jobId: string,
    attemptCount: number,
    guardId: string | null,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:attachment-sync|commit_delete_guard", {
          operationId,
          jobId,
          attemptCount,
          guardId,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async reconcileDeleteGuards(): Promise<Result<number, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE(
          "plugin:attachment-sync|reconcile_delete_guards",
        ),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async beginAttachmentDownload(
    operationId: string,
    scopeId: string | null,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE(
          "plugin:attachment-sync|begin_attachment_download",
          { operationId, scopeId },
        ),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async cancelAttachmentDownload(
    operationId: string,
  ): Promise<Result<boolean, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE(
          "plugin:attachment-sync|cancel_attachment_download",
          { operationId },
        ),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async downloadAndRestore(
    operationId: string,
    jobId: string,
    attemptCount: number,
    objectId: string,
    signedUrl: string,
    ciphertextSha256: string,
    ciphertextSizeBytes: number,
    formatVersion: number,
  ): Promise<Result<RestoredAttachment, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE(
          "plugin:attachment-sync|download_and_restore",
          {
            operationId,
            jobId,
            attemptCount,
            objectId,
            signedUrl,
            ciphertextSha256,
            ciphertextSizeBytes,
            formatVersion,
          },
        ),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async cleanupTransferCache(
    jobId: string,
    attemptCount: number,
    expectedCacheId: string,
  ): Promise<Result<boolean, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE(
          "plugin:attachment-sync|cleanup_transfer_cache",
          { jobId, attemptCount, expectedCacheId },
        ),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async downloadSharedAttachment(
    operationId: string,
    scopeId: string,
    attachmentId: string,
    signedUrl: string,
    expectedSha256: string,
    expectedSizeBytes: number,
  ): Promise<Result<SharedAttachmentCacheResult, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE(
          "plugin:attachment-sync|download_shared_attachment",
          {
            operationId,
            scopeId,
            attachmentId,
            signedUrl,
            expectedSha256,
            expectedSizeBytes,
          },
        ),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async sharedAttachmentPath(
    scopeId: string,
    attachmentId: string,
  ): Promise<Result<string | null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE(
          "plugin:attachment-sync|shared_attachment_path",
          { scopeId, attachmentId },
        ),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async removeSharedAttachment(
    scopeId: string,
    attachmentId: string,
  ): Promise<Result<boolean, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE(
          "plugin:attachment-sync|remove_shared_attachment",
          { scopeId, attachmentId },
        ),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async clearSharedAttachmentScope(
    scopeId: string,
  ): Promise<Result<number, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE(
          "plugin:attachment-sync|clear_shared_attachment_scope",
          { scopeId },
        ),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async clearSharedAttachmentPreviewScopes(): Promise<Result<boolean, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE(
          "plugin:attachment-sync|clear_shared_attachment_preview_scopes",
        ),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
};

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

export type DeleteGuardOutcome =
  | { kind: "skip" }
  | { kind: "deleteDirectly" }
  | { kind: "deleteWithGuard"; guardId: string };
export type PreparedDeleteGuard = {
  attachmentRef: string;
  versionRef: string;
  outcome: DeleteGuardOutcome;
};
export type PreparedSharedUpload = {
  cacheId: string;
  sha256: string;
  sizeBytes: number;
};
export type PreparedUpload = {
  cacheId: string;
  ciphertextSha256: string;
  ciphertextSizeBytes: number;
};
export type RestoredAttachment = {
  attachmentId: string;
  sessionId: string;
  relativePath: string;
  sizeBytes: number;
  sha256: string;
};
export type SharedAttachmentCacheResult = {
  cacheId: string;
  localPath: string;
  sizeBytes: number;
  sha256: string;
};
export type SharedUploadVersion = {
  sha256: string;
  sizeBytes: number;
  filename: string;
  contentType: string;
  cloudObjectKey: string;
};
export type UploadDescriptor = {
  attachmentRef: string;
  versionRef: string;
  ciphertextSizeBytes: number;
  formatVersion: number;
};

/** tauri-specta globals **/

import {
  invoke as TAURI_INVOKE,
  Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
  listen: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
  once: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
  | { status: "ok"; data: T }
  | { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
  mappings: Record<keyof T, string>,
) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__<T[K]> & {
        (handle: __WebviewWindow__): __EventObj__<T[K]>;
      };
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T];

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg),
          }),
          get: (_, command: keyof __EventObj__<any>) => {
            switch (command) {
              case "listen":
                return (arg: any) => TAURI_API_EVENT.listen(name, arg);
              case "once":
                return (arg: any) => TAURI_API_EVENT.once(name, arg);
              case "emit":
                return (arg: any) => TAURI_API_EVENT.emit(name, arg);
            }
          },
        });
      },
    },
  );
}
