// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async startCallbackServer(scheme: string, port: number | null) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:deeplink2|start_callback_server", { scheme, port }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopCallbackServer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:deeplink2|stop_callback_server") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async takePendingDeepLinks() : Promise<Result<DeepLink[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:deeplink2|take_pending_deep_links") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPendingShareOpens() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:deeplink2|list_pending_share_opens") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async takePendingShareOpen(pendingId: string) : Promise<Result<ShareOpenRequest | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:deeplink2|take_pending_share_open", { pendingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
deepLinkEvent: DeepLinkEvent,
shareOpenPendingEvent: ShareOpenPendingEvent
}>({
deepLinkEvent: "plugin:deeplink2:deep-link-event",
shareOpenPendingEvent: "plugin:deeplink2:share-open-pending-event"
})

/** user-defined constants **/



/** user-defined types **/

export type AuthCallbackSearch = { access_token?: string; refresh_token?: string; code?: string | null; state?: string | null }
export type BillingRefreshSearch = Record<string, never>
export type DeepLink = { to: "/auth/callback"; search: AuthCallbackSearch } | { to: "/billing/refresh"; search: BillingRefreshSearch } | { to: "/integration/callback"; search: IntegrationCallbackSearch } | { to: "/onboarding-demo/complete"; search: OnboardingDemoCompleteSearch }
export type DeepLinkEvent = DeepLink
export type IntegrationCallbackSearch = { integration_id: string; status: string; disconnected_connection_id: string | null; return_to: string | null }
export type OnboardingDemoCompleteSearch = Record<string, never>
export type ShareOpenPendingEvent = { pending_id: string }
export type ShareOpenRequest = { mode: "account"; share_id: string } | { mode: "handoff"; request_id: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
