mod commands;
mod error;
mod ext;
mod manifest;

pub use error::{Error, Result};
pub use ext::*;

const PLUGIN_NAME: &str = "fs2";

fn make_specta_builder<R: tauri::Runtime>() -> tauri_specta::Builder<R> {
    tauri_specta::Builder::<R>::new()
        .plugin_name(PLUGIN_NAME)
        .commands(tauri_specta::collect_commands![
            commands::read_text_file::<tauri::Wry>,
            commands::remove::<tauri::Wry>,
            commands::write_text_file,
        ])
        .error_handling(tauri_specta::ErrorHandlingMode::Result)
}

pub fn init<R: tauri::Runtime>() -> tauri::plugin::TauriPlugin<R> {
    let specta_builder = make_specta_builder();

    tauri::plugin::Builder::new(PLUGIN_NAME)
        .invoke_handler(specta_builder.invoke_handler())
        .build()
}

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn command_manifest_is_single_source() {
        let mut manifest_commands: Vec<String> = crate::manifest::COMMANDS
            .iter()
            .map(|command| command.to_string())
            .collect();
        manifest_commands.sort_unstable();

        // Export to a private path: export_types rewrites js/bindings.gen.ts
        // concurrently, so reading the shared file here would race with it.
        let bindings_path = std::env::temp_dir().join(format!(
            "anlg-{PLUGIN_NAME}-manifest-sync-{}.ts",
            std::process::id()
        ));
        make_specta_builder::<tauri::Wry>()
            .export(
                specta_typescript::Typescript::default()
                    .bigint(specta_typescript::BigIntExportBehavior::Number),
                &bindings_path,
            )
            .unwrap();
        let bindings = std::fs::read_to_string(&bindings_path).unwrap();
        let _ = std::fs::remove_file(&bindings_path);
        let prefix = format!("plugin:{PLUGIN_NAME}|");
        let mut binding_commands: Vec<String> = bindings
            .split(prefix.as_str())
            .skip(1)
            .filter_map(|rest| rest.split('"').next().map(str::to_string))
            .collect();
        binding_commands.sort_unstable();
        binding_commands.dedup();
        assert_eq!(
            binding_commands, manifest_commands,
            "generated bindings drifted from src/manifest.rs"
        );

        let mut permission_commands: Vec<String> =
            std::fs::read_dir("./permissions/autogenerated/commands")
                .unwrap()
                .map(|entry| entry.unwrap().path())
                .filter(|path| path.extension().is_some_and(|ext| ext == "toml"))
                .filter_map(|path| {
                    path.file_stem()
                        .map(|stem| stem.to_string_lossy().into_owned())
                })
                .collect();
        permission_commands.sort_unstable();
        assert_eq!(
            permission_commands, manifest_commands,
            "generated permissions drifted from src/manifest.rs"
        );
    }

    #[test]
    fn export_types() {
        const OUTPUT_FILE: &str = "./js/bindings.gen.ts";

        make_specta_builder::<tauri::Wry>()
            .export(
                specta_typescript::Typescript::default()
                    .formatter(specta_typescript::formatter::prettier)
                    .bigint(specta_typescript::BigIntExportBehavior::Number),
                OUTPUT_FILE,
            )
            .unwrap();

        let content = std::fs::read_to_string(OUTPUT_FILE).unwrap();
        std::fs::write(OUTPUT_FILE, format!("// @ts-nocheck\n{content}")).unwrap();
    }
}
