// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  async deserialize(input: string): Promise<Result<ParsedDocument, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|deserialize", { input }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async writeJsonBatch(
    items: [JsonValue, string][],
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|write_json_batch", { items }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async writeDocumentBatch(
    items: [ParsedDocument, string][],
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|write_document_batch", {
          items,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async readDocumentBatch(
    dirPath: string,
  ): Promise<Result<Partial<{ [key in string]: ParsedDocument }>, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|read_document_batch", {
          dirPath,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async listFolders(): Promise<Result<ListFoldersResult, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|list_folders"),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async moveSession(
    sessionId: string,
    fromFolderPath: string,
    targetFolderPath: string,
  ): Promise<Result<MoveSessionResult, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|move_session", {
          sessionId,
          fromFolderPath,
          targetFolderPath,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async createFolder(folderPath: string): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|create_folder", {
          folderPath,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async renameFolder(
    oldPath: string,
    newPath: string,
  ): Promise<Result<RenameFolderResult, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|rename_folder", {
          oldPath,
          newPath,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async deleteFolder(folderPath: string): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|delete_folder", {
          folderPath,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async audioExist(sessionId: string): Promise<Result<boolean, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|audio_exist", { sessionId }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async audioDelete(sessionId: string): Promise<Result<boolean, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|audio_delete", { sessionId }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async audioMetadata(
    sessionId: string,
  ): Promise<Result<AudioFileMetadata | null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|audio_metadata", {
          sessionId,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async audioDeleteOrphanedExpired(
    knownSessionIds: string[],
    retentionMs: number,
    nowMs: number,
  ): Promise<Result<string[], string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE(
          "plugin:fs-sync|audio_delete_orphaned_expired",
          { knownSessionIds, retentionMs, nowMs },
        ),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async audioImport(
    sessionId: string,
    sourcePath: string,
  ): Promise<Result<string, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|audio_import", {
          sessionId,
          sourcePath,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async audioImportData(
    sessionId: string,
    data: number[],
    filename: string,
    contentType: string | null,
  ): Promise<Result<string, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|audio_import_data", {
          sessionId,
          data,
          filename,
          contentType,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async audioSourceMetadata(
    sourcePath: string,
  ): Promise<Result<AudioSourceMetadata, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|audio_source_metadata", {
          sourcePath,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async audioPath(sessionId: string): Promise<Result<string, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|audio_path", { sessionId }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async audioCopy(
    sourceSessionId: string,
    targetSessionId: string,
  ): Promise<Result<boolean, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|audio_copy", {
          sourceSessionId,
          targetSessionId,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async sessionDir(sessionId: string): Promise<Result<string, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|session_dir", { sessionId }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async loadSessionContent(
    sessionId: string,
  ): Promise<Result<SessionContentData, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|load_session_content", {
          sessionId,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async deleteSessionFolder(sessionId: string): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|delete_session_folder", {
          sessionId,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async scanAndRead(
    scanDir: string,
    filePatterns: string[],
    recursive: boolean,
    pathFilter: string | null,
  ): Promise<Result<ScanResult, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|scan_and_read", {
          scanDir,
          filePatterns,
          recursive,
          pathFilter,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async chatDir(chatGroupId: string): Promise<Result<string, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|chat_dir", { chatGroupId }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async entityDir(dirName: string): Promise<Result<string, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|entity_dir", { dirName }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async attachmentSave(
    sessionId: string,
    data: number[],
    filename: string,
  ): Promise<Result<AttachmentSaveResult, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|attachment_save", {
          sessionId,
          data,
          filename,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async attachmentList(
    sessionId: string,
  ): Promise<Result<AttachmentInfo[], string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|attachment_list", {
          sessionId,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async attachmentRead(
    sessionId: string,
    attachmentId: string,
  ): Promise<Result<number[], string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|attachment_read", {
          sessionId,
          attachmentId,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async attachmentRemove(
    sessionId: string,
    attachmentId: string,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:fs-sync|attachment_remove", {
          sessionId,
          attachmentId,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
};

/** user-defined events **/

export const events = __makeEvents__<{
  audioImportEvent: AudioImportEvent;
}>({
  audioImportEvent: "plugin:fs-sync:audio-import-event",
});

/** user-defined constants **/

/** user-defined types **/

export type AttachmentInfo = {
  attachmentId: string;
  path: string;
  extension: string;
  modifiedAt: string;
};
export type AttachmentSaveResult = { path: string; attachmentId: string };
export type AudioFileMetadata = {
  filename: string;
  contentType: string;
  sizeBytes: number;
  sha256: string;
};
export type AudioImportEvent =
  | { type: "audioImportStarted"; session_id: string }
  | { type: "audioImportProgress"; session_id: string; percentage: number }
  | { type: "audioImportCompleted"; session_id: string }
  | { type: "audioImportFailed"; session_id: string; error: string };
export type AudioSourceMetadata = {
  createdAt: string | null;
  modifiedAt: string | null;
  durationMs: number | null;
};
export type FolderInfo = { name: string; parent_folder_id: string | null };
export type FolderSessionUpdate = { sessionId: string; folderId: string };
export type JsonValue =
  | null
  | boolean
  | number
  | string
  | JsonValue[]
  | Partial<{ [key in string]: JsonValue }>;
export type ListFoldersResult = {
  folders: Partial<{ [key in string]: FolderInfo }>;
  session_folder_map: Partial<{ [key in string]: string }>;
};
export type MoveSessionResult = { sessionId: string; folderId: string };
export type ParsedDocument = {
  frontmatter: Partial<{ [key in string]: JsonValue }>;
  content: string;
};
export type RenameFolderResult = { updates: FolderSessionUpdate[] };
export type ScanResult = {
  files: Partial<{ [key in string]: string }>;
  dirs: string[];
};
export type SessionContentData = {
  sessionId: string;
  meta: SessionMetaData | null;
  rawMemoTiptapJson: JsonValue | null;
  rawMemoMarkdown: string | null;
  transcript: TranscriptJson | null;
  notes: SessionNoteData[];
};
export type SessionMetaData = {
  id: string;
  userId: string;
  createdAt: string | null;
  title: string | null;
  event: JsonValue | null;
  eventId: string | null;
  participants: SessionMetaParticipant[];
  tags: string[];
};
export type SessionMetaParticipant = {
  id: string;
  userId: string;
  sessionId: string;
  humanId: string;
  source: string;
};
export type SessionNoteData = {
  id: string;
  sessionId: string;
  templateId: string | null;
  position: number | null;
  title: string | null;
  tiptapJson: JsonValue;
  markdown: string | null;
};
export type TranscriptJson = { transcripts?: TranscriptWithData[] };
export type TranscriptSpeakerHint = {
  id?: string | null;
  word_id: string;
  type: string;
  value?: JsonValue;
};
export type TranscriptWithData = {
  id: string;
  user_id?: string;
  created_at?: string;
  session_id: string;
  started_at?: number;
  ended_at?: number | null;
  memo_md?: string;
  words?: TranscriptWord[];
  speaker_hints?: TranscriptSpeakerHint[];
};
export type TranscriptWord = {
  id?: string | null;
  text: string;
  start_ms: number;
  end_ms: number;
  channel: number;
  speaker?: string | null;
  metadata?: Partial<{ [key in string]: JsonValue }> | null;
};

/** tauri-specta globals **/

import {
  invoke as TAURI_INVOKE,
  Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
  listen: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
  once: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
  | { status: "ok"; data: T }
  | { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
  mappings: Record<keyof T, string>,
) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__<T[K]> & {
        (handle: __WebviewWindow__): __EventObj__<T[K]>;
      };
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T];

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg),
          }),
          get: (_, command: keyof __EventObj__<any>) => {
            switch (command) {
              case "listen":
                return (arg: any) => TAURI_API_EVENT.listen(name, arg);
              case "once":
                return (arg: any) => TAURI_API_EVENT.once(name, arg);
              case "emit":
                return (arg: any) => TAURI_API_EVENT.emit(name, arg);
            }
          },
        });
      },
    },
  );
}
