// Generated by uniffi-bindgen-react-native
#include <jni.h>
#include <jsi/jsi.h>
#include <ReactCommon/CallInvokerHolder.h>
#include "anlg-mobile-bridge.h"

namespace jsi = facebook::jsi;
namespace react = facebook::react;

// Automated testing checks Java_so_anarlog_mobilebridge_MobileBridgeModule and anlg_mobilebridge
// by comparing the whole line here.
/*
Java_so_anarlog_mobilebridge_MobileBridgeModule_nativeMultiply(JNIEnv *env, jclass type, jdouble a, jdouble b) {
    return anlg_mobilebridge::multiply(a, b);
}
*/

// Installer coming from MobileBridgeModule
extern "C"
JNIEXPORT jboolean JNICALL
Java_so_anarlog_mobilebridge_MobileBridgeModule_nativeInstallRustCrate(
    JNIEnv *env,
    jclass type,
    jlong rtPtr,
    jobject callInvokerHolderJavaObj
) {
    using JCallInvokerHolder = facebook::react::CallInvokerHolder;

    auto holderLocal = facebook::jni::make_local(callInvokerHolderJavaObj);
    auto holderRef = facebook::jni::static_ref_cast<JCallInvokerHolder::javaobject>(holderLocal);
    auto* holderCxx = holderRef->cthis();
    auto jsCallInvoker = holderCxx->getCallInvoker();
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);

    return anlg_mobilebridge::installRustCrate(*runtime, jsCallInvoker);
}

extern "C"
JNIEXPORT jboolean JNICALL
Java_so_anarlog_mobilebridge_MobileBridgeModule_nativeCleanupRustCrate(JNIEnv *env, jclass type, jlong rtPtr) {
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return anlg_mobilebridge::cleanupRustCrate(*runtime);
}