[package]
name = "audio-chunking"
version = "0.1.0"
edition = "2024"

[features]
default = ["vad"]
vad = [
  "dep:futures-util",
  "dep:anlg-audio-interface",
  "dep:anlg-onnx",
  "dep:anlg-vad",
  "dep:pin-project",
]
segmentation = []

[dev-dependencies]
anlg-data = { workspace = true }
futures-util = { workspace = true }
hound = { workspace = true }
rodio = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[[example]]
name = "chunking"
required-features = ["vad"]

[dependencies]
anlg-audio-interface = { workspace = true, optional = true }
anlg-onnx = { workspace = true, optional = true }
anlg-vad = { workspace = true, features = ["silero-onnx"], optional = true }

futures-util = { workspace = true, optional = true }
pin-project = { workspace = true, optional = true }
thiserror = { workspace = true }
