runs:
  using: "composite"
  steps:
    - if: runner.os == 'Linux'
      shell: bash
      run: |
        curl -1sLf 'https://artifacts-cli.infisical.com/setup.deb.sh' | sudo -E bash
        sudo apt-get install -y infisical
    - if: runner.os == 'macOS'
      shell: bash
      run: brew install infisical/get-cli/infisical
