// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async check() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:updater2|check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async download(version: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:updater2|download", { version }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installAndRelaunch(version: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:updater2|install_and_relaunch", { version }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isDownloaded(version: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:updater2|is_downloaded", { version }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAutomaticUpdatesEnabled(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:updater2|set_automatic_updates_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setMeetingActive(active: boolean) : Promise<void> {
    await TAURI_INVOKE("plugin:updater2|set_meeting_active", { active });
},
async maybeEmitUpdated() : Promise<void> {
    await TAURI_INVOKE("plugin:updater2|maybe_emit_updated");
}
}

/** user-defined events **/


export const events = __makeEvents__<{
updateAvailableEvent: UpdateAvailableEvent,
updateDownloadFailedEvent: UpdateDownloadFailedEvent,
updateDownloadProgressEvent: UpdateDownloadProgressEvent,
updateDownloadingEvent: UpdateDownloadingEvent,
updateReadyEvent: UpdateReadyEvent,
updatedEvent: UpdatedEvent
}>({
updateAvailableEvent: "plugin:updater2:update-available-event",
updateDownloadFailedEvent: "plugin:updater2:update-download-failed-event",
updateDownloadProgressEvent: "plugin:updater2:update-download-progress-event",
updateDownloadingEvent: "plugin:updater2:update-downloading-event",
updateReadyEvent: "plugin:updater2:update-ready-event",
updatedEvent: "plugin:updater2:updated-event"
})

/** user-defined constants **/



/** user-defined types **/

export type UpdateAvailableEvent = { version: string }
export type UpdateDownloadFailedEvent = { version: string }
export type UpdateDownloadProgressEvent = { version: string; chunk_length: number; content_length: number | null }
export type UpdateDownloadingEvent = { version: string }
export type UpdateReadyEvent = { version: string }
export type UpdatedEvent = { previous: string | null; current: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
