/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppLiveCaptionRouteImport } from './routes/app/live-caption'
import { Route as AppInstructionRouteImport } from './routes/app/instruction'
import { Route as AppFloatingBarRouteImport } from './routes/app/floating-bar'
import { Route as AppComposerRouteImport } from './routes/app/composer'
import { Route as AppNoteSessionIdRouteImport } from './routes/app/note.$sessionId'
import { Route as AppMainLayoutRouteImport } from './routes/app/main/_layout'
import { Route as AppMainLayoutIndexRouteImport } from './routes/app/main/_layout.index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLiveCaptionRoute = AppLiveCaptionRouteImport.update({
  id: '/live-caption',
  path: '/live-caption',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInstructionRoute = AppInstructionRouteImport.update({
  id: '/instruction',
  path: '/instruction',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFloatingBarRoute = AppFloatingBarRouteImport.update({
  id: '/floating-bar',
  path: '/floating-bar',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppComposerRoute = AppComposerRouteImport.update({
  id: '/composer',
  path: '/composer',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNoteSessionIdRoute = AppNoteSessionIdRouteImport.update({
  id: '/note/$sessionId',
  path: '/note/$sessionId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMainLayoutRoute = AppMainLayoutRouteImport.update({
  id: '/main/_layout',
  path: '/main',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMainLayoutIndexRoute = AppMainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMainLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteRouteWithChildren
  '/app/composer': typeof AppComposerRoute
  '/app/floating-bar': typeof AppFloatingBarRoute
  '/app/instruction': typeof AppInstructionRoute
  '/app/live-caption': typeof AppLiveCaptionRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/': typeof AppIndexRoute
  '/app/main': typeof AppMainLayoutRouteWithChildren
  '/app/note/$sessionId': typeof AppNoteSessionIdRoute
  '/app/main/': typeof AppMainLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/app/composer': typeof AppComposerRoute
  '/app/floating-bar': typeof AppFloatingBarRoute
  '/app/instruction': typeof AppInstructionRoute
  '/app/live-caption': typeof AppLiveCaptionRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app': typeof AppIndexRoute
  '/app/note/$sessionId': typeof AppNoteSessionIdRoute
  '/app/main': typeof AppMainLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteRouteWithChildren
  '/app/composer': typeof AppComposerRoute
  '/app/floating-bar': typeof AppFloatingBarRoute
  '/app/instruction': typeof AppInstructionRoute
  '/app/live-caption': typeof AppLiveCaptionRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/': typeof AppIndexRoute
  '/app/main/_layout': typeof AppMainLayoutRouteWithChildren
  '/app/note/$sessionId': typeof AppNoteSessionIdRoute
  '/app/main/_layout/': typeof AppMainLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/app/composer'
    | '/app/floating-bar'
    | '/app/instruction'
    | '/app/live-caption'
    | '/app/onboarding'
    | '/app/'
    | '/app/main'
    | '/app/note/$sessionId'
    | '/app/main/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app/composer'
    | '/app/floating-bar'
    | '/app/instruction'
    | '/app/live-caption'
    | '/app/onboarding'
    | '/app'
    | '/app/note/$sessionId'
    | '/app/main'
  id:
    | '__root__'
    | '/app'
    | '/app/composer'
    | '/app/floating-bar'
    | '/app/instruction'
    | '/app/live-caption'
    | '/app/onboarding'
    | '/app/'
    | '/app/main/_layout'
    | '/app/note/$sessionId'
    | '/app/main/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/live-caption': {
      id: '/app/live-caption'
      path: '/live-caption'
      fullPath: '/app/live-caption'
      preLoaderRoute: typeof AppLiveCaptionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/instruction': {
      id: '/app/instruction'
      path: '/instruction'
      fullPath: '/app/instruction'
      preLoaderRoute: typeof AppInstructionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/floating-bar': {
      id: '/app/floating-bar'
      path: '/floating-bar'
      fullPath: '/app/floating-bar'
      preLoaderRoute: typeof AppFloatingBarRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/composer': {
      id: '/app/composer'
      path: '/composer'
      fullPath: '/app/composer'
      preLoaderRoute: typeof AppComposerRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/note/$sessionId': {
      id: '/app/note/$sessionId'
      path: '/note/$sessionId'
      fullPath: '/app/note/$sessionId'
      preLoaderRoute: typeof AppNoteSessionIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/main/_layout': {
      id: '/app/main/_layout'
      path: '/main'
      fullPath: '/app/main'
      preLoaderRoute: typeof AppMainLayoutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/main/_layout/': {
      id: '/app/main/_layout/'
      path: '/'
      fullPath: '/app/main/'
      preLoaderRoute: typeof AppMainLayoutIndexRouteImport
      parentRoute: typeof AppMainLayoutRoute
    }
  }
}

interface AppMainLayoutRouteChildren {
  AppMainLayoutIndexRoute: typeof AppMainLayoutIndexRoute
}

const AppMainLayoutRouteChildren: AppMainLayoutRouteChildren = {
  AppMainLayoutIndexRoute: AppMainLayoutIndexRoute,
}

const AppMainLayoutRouteWithChildren = AppMainLayoutRoute._addFileChildren(
  AppMainLayoutRouteChildren,
)

interface AppRouteRouteChildren {
  AppComposerRoute: typeof AppComposerRoute
  AppFloatingBarRoute: typeof AppFloatingBarRoute
  AppInstructionRoute: typeof AppInstructionRoute
  AppLiveCaptionRoute: typeof AppLiveCaptionRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMainLayoutRoute: typeof AppMainLayoutRouteWithChildren
  AppNoteSessionIdRoute: typeof AppNoteSessionIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppComposerRoute: AppComposerRoute,
  AppFloatingBarRoute: AppFloatingBarRoute,
  AppInstructionRoute: AppInstructionRoute,
  AppLiveCaptionRoute: AppLiveCaptionRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppIndexRoute: AppIndexRoute,
  AppMainLayoutRoute: AppMainLayoutRouteWithChildren,
  AppNoteSessionIdRoute: AppNoteSessionIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
