// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listMeetings(input: ListMeetingsInput) : Promise<Result<MeetingPage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|list_meetings", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMeeting(input: GetMeetingInput) : Promise<Result<Meeting, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|get_meeting", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMeetingTranscript(input: GetMeetingTranscriptInput) : Promise<Result<TranscriptPage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|get_meeting_transcript", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRecurringMeetingHistory(input: GetRecurringMeetingHistoryInput) : Promise<Result<MeetingPage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|get_recurring_meeting_history", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async execute(sql: string, params: JsonValue[]) : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|execute", { sql, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async executeTransaction(statements: TransactionStatement[]) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|execute_transaction", { statements }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async executeProxy(sql: string, params: JsonValue[], method: string) : Promise<Result<ExecuteProxyResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|execute_proxy", { sql, params, method }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLegacyImportReport() : Promise<Result<LegacyImportReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|get_legacy_import_report") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLegacyCleanupStatus() : Promise<Result<LegacyCleanupStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|get_legacy_cleanup_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cleanupLegacyFiles() : Promise<Result<LegacyCleanupResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|cleanup_legacy_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runLegacyImport(dryRun: boolean) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|run_legacy_import", { dryRun }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applySessionIngest(workspaceId: string, envelope: JsonValue) : Promise<Result<SessionIngestApplyResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|apply_session_ingest", { workspaceId, envelope }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getE2eeIdentityStatus(accountUserId: string) : Promise<Result<E2eeIdentityStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|get_e2ee_identity_status", { accountUserId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async inspectE2eeRecoveryKey(recoveryKey: string) : Promise<Result<E2eeRecoveryKeyIdentity, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|inspect_e2ee_recovery_key", { recoveryKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createE2eeIdentity(accountUserId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|create_e2ee_identity", { accountUserId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importE2eeIdentity(accountUserId: string, recoveryKey: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|import_e2ee_identity", { accountUserId, recoveryKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOrCreateE2eeDeviceIdentity(accountUserId: string) : Promise<Result<E2eeDeviceIdentity, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|get_or_create_e2ee_device_identity", { accountUserId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sealE2eeRecoveryKeyForDevice(accountUserId: string, requestId: string, recipientPublicKey: string) : Promise<Result<E2eeDeviceEnrollmentPackage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|seal_e2ee_recovery_key_for_device", { accountUserId, requestId, recipientPublicKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sealWorkspaceE2eeKeyForRecipients(accountUserId: string, workspaceId: string, recipients: WorkspaceE2eeKeyRecipient[], rotate: boolean, sourceGrant: CloudsyncWorkspaceKeyGrant | null) : Promise<Result<SealedWorkspaceE2eeKey, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|seal_workspace_e2ee_key_for_recipients", { accountUserId, workspaceId, recipients, rotate, sourceGrant }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importE2eeDeviceEnrollment(accountUserId: string, requestId: string, package: E2eeDeviceEnrollmentPackage) : Promise<Result<E2eeRecoveryKeyIdentity, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|import_e2ee_device_enrollment", { accountUserId, requestId, package }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async subscribe(sql: string, params: JsonValue[], onEvent: TAURI_CHANNEL<QueryEvent>) : Promise<Result<SubscriptionRegistration, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|subscribe", { sql, params, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unsubscribe(subscriptionId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|unsubscribe", { subscriptionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configureCloudsync(configJson: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|configure_cloudsync", { configJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async bindCloudsyncAccount(accountUserId: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|bind_cloudsync_account", { accountUserId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configureCloudsyncToken(databaseId: string, token: string, workspaceId: string, workspaceProjection: CloudsyncWorkspaceProjection | null, workspaceKeyGrants: CloudsyncWorkspaceKeyGrant[] | null, e2eeWitness: CloudsyncE2eeWitness) : Promise<Result<CloudsyncTokenConfigurationResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|configure_cloudsync_token", { databaseId, token, workspaceId, workspaceProjection, workspaceKeyGrants, e2eeWitness }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configureE2eeReplica(workspaceId: string, e2eeWitness: CloudsyncE2eeWitness) : Promise<Result<CloudsyncTokenConfigurationResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|configure_e2ee_replica", { workspaceId, e2eeWitness }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startCloudsync() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|start_cloudsync") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopCloudsync() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|stop_cloudsync") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async suspendCloudsync() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|suspend_cloudsync") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async suspendCloudsyncForSignOut() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|suspend_cloudsync_for_sign_out") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async suspendCloudsyncAfterAuthLoss() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|suspend_cloudsync_after_auth_loss") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCloudsyncStatus() : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|get_cloudsync_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async syncCloudsyncNow() : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|sync_cloudsync_now") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async beginCloudsyncActivity(activity: string, key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|begin_cloudsync_activity", { activity, key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async endCloudsyncActivity(activity: string, key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|end_cloudsync_activity", { activity, key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getStartupStatus() : Promise<StartupStatus> {
    return await TAURI_INVOKE("plugin:db|get_startup_status");
},
async waitUntilReady() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|wait_until_ready") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ActionItem = { id: string; assignee_human_id: string; status: string; text: string; due_at: string; completed_at: string | null }
export type CloudsyncE2eeWitness = { endpoint: string; accessToken: string }
export type CloudsyncTokenConfigurationResult = "configured" | "account_mismatch"
export type CloudsyncWorkspaceKeyGrant = { workspaceId: string; keyId: string; ephemeralPublicKey: string; nonce: string; ciphertext: string; isActive: boolean }
export type CloudsyncWorkspaceProjection = { accountUserId: string; personalWorkspaceId: string; workspaces: CloudsyncWorkspaceProjectionEntry[] }
export type CloudsyncWorkspaceProjectionEntry = { id: string; ownerUserId: string; kind: string; name: string; membershipId: string; role: string; membershipCreatedAt: string; membershipUpdatedAt: string; createdAt: string; updatedAt: string }
export type DependencyAnalysis = { kind: "reactive"; data: { targets: DependencyTarget[] } } | { kind: "non_reactive"; data: { reason: string } }
export type DependencyTarget = { kind: "table"; data: string } | { kind: "virtual_table"; data: string }
export type Document = { id: string; kind: string; template_id: string; title: string; markdown: string; sort_order: number; created_at: string; updated_at: string }
export type E2eeDeviceEnrollmentPackage = { ephemeralPublicKey: string; nonce: string; ciphertext: string }
export type E2eeDeviceIdentity = { publicKey: string }
export type E2eeIdentityStatus = { configured: boolean; keyId: string | null; memberPublicKey: string | null }
export type E2eeRecoveryKeyIdentity = { keyId: string }
export type ExecuteProxyResult = { rows: JsonValue[] }
export type GetMeetingInput = { meeting_id: string }
export type GetMeetingTranscriptInput = { meeting_id: string; offset: number | null; limit: number | null }
export type GetRecurringMeetingHistoryInput = { meeting_id: string; limit: number | null; offset: number | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type LegacyCleanupResult = { deletedFileCount: number; deletedBytes: number }
export type LegacyCleanupStatus = { migrationReady: boolean; migrationVerified: boolean; available: boolean; alreadyCleaned: boolean; fileCount: number; totalBytes: number; sourceRoot: string; blockingReason: string | null }
export type LegacyImportItemReport = { sourcePath: string; sourceKind: string; sourceSha256: string; status: string; discoveredCount: number; importedCount: number; matchedCount: number; skippedCount: number; conflictCount: number; error: string }
export type LegacyImportReport = { state: StorageMigrationState; latestRun: LegacyImportRun | null; items: LegacyImportItemReport[]; targets: LegacyImportTargetReport[] }
export type LegacyImportRun = { id: string; importerVersion: number; sourceRoot: string; dryRun: boolean; status: string; discoveredCount: number; importedCount: number; matchedCount: number; skippedCount: number; conflictCount: number; errorCount: number; startedAt: string; completedAt: string | null; error: string }
export type LegacyImportTargetReport = { sourcePath: string; tableName: string; targetId: string; status: string; error: string }
export type ListMeetingsInput = { query: string | null; series_id: string | null; limit: number | null; offset: number | null }
export type Meeting = { id: string; title: string; kind: string; status: string; created_at: string; updated_at: string; started_at: string; ended_at: string; timezone: string; language: string; series_id: string; note: Document | null; summaries: Document[]; participants: Participant[]; action_items: ActionItem[] }
export type MeetingListItem = { id: string; title: string; kind: string; status: string; created_at: string; updated_at: string; started_at: string; ended_at: string; series_id: string }
export type MeetingPage = { meetings: MeetingListItem[]; pagination: Pagination }
export type Pagination = { offset: number; limit: number; returned: number; total: number | null; next_offset: number | null }
export type Participant = { human_id: string; display_name: string; email: string; role: string; job_title: string; organization_id: string; organization_name: string }
export type QueryEvent = { event: "result"; data: JsonValue[] } | { event: "error"; data: string }
export type SealedWorkspaceE2eeKey = { keyId: string; grants: WorkspaceE2eeKeyGrantUpload[] }
export type SessionIngestApplyResult = "applied" | "already_applied" | "rejected"
export type StartupPhase = "preparing_database" | "migrating_database" | "importing_legacy_data" | "configuring_cloudsync" | "ready" | "failed"
export type StartupStatus = { phase: StartupPhase; migrationCurrent: number | null; migrationTotal: number | null }
export type StorageMigrationState = { phase: string; latestRunId: string; parityVerified: boolean; cutoverAt: string | null; rollbackUntil: string | null; lastError: string; updatedAt: string }
export type SubscriptionRegistration = { id: string; analysis: DependencyAnalysis }
export type TAURI_CHANNEL<TSend> = null
export type TransactionStatement = { sql: string; params: JsonValue[]; expectedRowsAffected?: number | null }
export type TranscriptPage = { meeting_id: string; text: string; words: JsonValue[]; pagination: Pagination }
export type WorkspaceE2eeKeyGrantUpload = { userId: string; ephemeralPublicKey: string; nonce: string; ciphertext: string }
export type WorkspaceE2eeKeyRecipient = { userId: string; publicKey: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
