[package]
name = "local-model"
version = "0.1.0"
edition = "2024"

[dependencies]
anlg-am = { workspace = true }
anlg-file = { workspace = true }
anlg-model-downloader = { workspace = true }
anlg-transcribe-soniqo = { workspace = true }
anlg-transcribe-speechanalyzer = { workspace = true }
anlg-whisper-local-model = { workspace = true }

serde = { workspace = true }
specta = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
