// Generated by uniffi-bindgen-react-native
#include "anlg-mobile-bridge.h"
#include "generated/mobile_bridge.hpp"

namespace anlg_mobilebridge {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeMobileBridge::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}