[package]
name = "api-subscription"
version = "0.1.0"
edition = "2024"

[dependencies]
anlg-analytics = { workspace = true }
anlg-api-auth = { workspace = true }
anlg-api-env = { workspace = true }
anlg-api-error = { workspace = true }
anlg-loops = { workspace = true }
anlg-observability = { workspace = true }
anlg-supabase-storage = { workspace = true }

utoipa = { workspace = true }

axum = { workspace = true }
reqwest = { workspace = true, features = ["json", "stream"] }
sentry = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }

chrono = { workspace = true }
futures-util = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
urlencoding = { workspace = true }
uuid = { workspace = true }

backon = { workspace = true }

async-stripe = { workspace = true }
async-stripe-billing = { workspace = true, features = ["subscription"] }
async-stripe-core = { workspace = true, features = ["customer"] }

[dev-dependencies]
tower = { workspace = true }
wiremock = { workspace = true }
