// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async captureFrontmostWindowContext(options: WindowContextCaptureOptions | null) : Promise<Result<WindowContextCapture, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:screen|capture_frontmost_window_context", { options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async captureTargetWindowContext(target: WindowCaptureTarget, options: WindowContextCaptureOptions | null) : Promise<Result<WindowContextCapture, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:screen|capture_target_window_context", { target, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type CaptureRect = { x: number; y: number; width: number; height: number }
export type CaptureStrategy = "window_only" | "window_with_context" | "display"
export type CaptureSubject = { kind: "window"; window: WindowContextMetadata } | { kind: "display"; display: DisplayContextMetadata }
export type DisplayContextMetadata = { id: number; name: string; rect: CaptureRect; isPrimary: boolean }
export type WindowCaptureTarget = { pid: number; appName: string | null; title: string | null }
export type WindowContextCapture = { mimeType: string; dataBase64: string; capturedAtMs: number; width: number; height: number; strategy: CaptureStrategy; crop: CaptureRect; subject: CaptureSubject }
export type WindowContextCaptureOptions = { imagePolicy: WindowContextImagePolicy | null }
export type WindowContextImagePolicy = { maxLongSide: number | null }
export type WindowContextMetadata = { id: number; pid: number; appName: string; title: string; rect: CaptureRect }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
