// @ts-nocheck
/** tauri-specta globals **/
import {
  Channel as TAURI_CHANNEL,
  invoke as TAURI_INVOKE,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  async listInputDevices(): Promise<Result<AudioDevice[], string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:audio-priority|list_input_devices"),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async listOutputDevices(): Promise<Result<AudioDevice[], string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:audio-priority|list_output_devices"),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async setDefaultInputDevice(deviceId: string): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE(
          "plugin:audio-priority|set_default_input_device",
          { deviceId },
        ),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async setDefaultOutputDevice(
    deviceId: string,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE(
          "plugin:audio-priority|set_default_output_device",
          { deviceId },
        ),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getInputPriorities(): Promise<Result<string[], string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:audio-priority|get_input_priorities"),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getOutputPriorities(): Promise<Result<string[], string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:audio-priority|get_output_priorities"),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async saveInputPriorities(
    priorities: string[],
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE(
          "plugin:audio-priority|save_input_priorities",
          { priorities },
        ),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async saveOutputPriorities(
    priorities: string[],
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE(
          "plugin:audio-priority|save_output_priorities",
          { priorities },
        ),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
};

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

export type AudioDevice = {
  id: DeviceId;
  name: string;
  direction: AudioDirection;
  transport_type: TransportType;
  is_default: boolean;
  volume?: number | null;
  is_muted?: boolean | null;
};
export type AudioDirection = "Input" | "Output";
export type DeviceId = string;
/**
 * Transport type for audio devices.
 *
 * Used to determine device type and priority.
 */
export type TransportType =
  | "BuiltIn"
  | "Usb"
  | "Bluetooth"
  | "Hdmi"
  | "Pci"
  | "Virtual"
  | "Unknown";

type __EventObj__<T> = {
  listen: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
  once: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
  | { status: "ok"; data: T }
  | { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
  mappings: Record<keyof T, string>,
) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__<T[K]> & {
        (handle: __WebviewWindow__): __EventObj__<T[K]>;
      };
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T];

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg),
          }),
          get: (_, command: keyof __EventObj__<any>) => {
            switch (command) {
              case "listen":
                return (arg: any) => TAURI_API_EVENT.listen(name, arg);
              case "once":
                return (arg: any) => TAURI_API_EVENT.once(name, arg);
              case "emit":
                return (arg: any) => TAURI_API_EVENT.emit(name, arg);
            }
          },
        });
      },
    },
  );
}
