[package]
name = "embedding"
version = "0.1.0"
edition = "2024"

[features]
default = ["onnx"]
onnx = ["dep:anlg-onnx", "dep:knf-rs"]
coreml = ["onnx", "anlg-onnx/coreml"]
directml = ["onnx", "anlg-onnx/directml"]

[dependencies]
anlg-onnx = { workspace = true, optional = true }
knf-rs = { git = "https://github.com/thewh1teagle/pyannote-rs", rev = "e23bd29", package = "knf-rs", optional = true }

serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
anlg-data = { workspace = true }
approx = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
